-- Migration: Add missing columns (category_color, url, notes) to password_entries table to fix the saving error. Also ensures user_id column exists.
-- Executed at: 2025-11-22T16:41:47Z
-- Generated by AI Agent

ALTER TABLE password_entries 
ADD COLUMN IF NOT EXISTS category_color TEXT DEFAULT 'ff2196f3',
ADD COLUMN IF NOT EXISTS url TEXT,
ADD COLUMN IF NOT EXISTS notes TEXT,
ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id);
