-- Migration: I will inspect the schema of the 'password_entries' table to identify the data type of the 'category_color' column. This will help confirm if the 'integer out of range' error is caused by a type mismatch (e.g., trying to store a large color value in an integer column instead of text).
-- Executed at: 2025-12-24T13:41:18Z
-- Generated by AI Agent

SELECT column_name, data_type, udt_name
FROM information_schema.columns 
WHERE table_name = 'password_entries';
