-- Migration: Create password_entries table with Row Level Security (RLS) enabled. This table will store user password data securely, linked to their Supabase Auth user ID. Policies ensure users can only create, view, update, and delete their own entries.
-- Executed at: 2025-11-22T15:49:27Z
-- Generated by AI Agent

-- Create the table
CREATE TABLE IF NOT EXISTS password_entries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  url TEXT,
  notes TEXT,
  category_color_value INTEGER NOT NULL DEFAULT 4280391411, -- Default to Colors.blue.value
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE password_entries ENABLE ROW LEVEL SECURITY;

-- Create Policies
-- 1. Select: Users can see their own data
CREATE POLICY "Users can view their own entries" 
ON password_entries FOR SELECT 
USING (auth.uid() = user_id);

-- 2. Insert: Users can insert their own data
CREATE POLICY "Users can insert their own entries" 
ON password_entries FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- 3. Update: Users can update their own data
CREATE POLICY "Users can update their own entries" 
ON password_entries FOR UPDATE 
USING (auth.uid() = user_id);

-- 4. Delete: Users can delete their own data
CREATE POLICY "Users can delete their own entries" 
ON password_entries FOR DELETE 
USING (auth.uid() = user_id);

