-- Migration: Recreating the category_color column as TEXT to definitively resolve the 'integer out of range' error. The previous attempt to alter the column might not have propagated correctly or the column type was still causing issues with hex string storage. This operation drops the problematic column and adds it back with the correct TEXT type, ensuring it can store color hex codes (e.g., 'ff2196f3') without numeric overflow.
-- Executed at: 2025-12-24T16:04:45Z
-- Generated by AI Agent

ALTER TABLE password_entries DROP COLUMN IF EXISTS category_color;
ALTER TABLE password_entries ADD COLUMN category_color text DEFAULT 'ff2196f3';
