-- Migration: Change category_color column type to text to prevent integer overflow errors when storing 32-bit color values (which can exceed the range of a standard SQL integer). This matches the Dart code which sends the color as a hex string.
-- Executed at: 2025-12-24T14:34:38Z
-- Generated by AI Agent

ALTER TABLE password_entries ALTER COLUMN category_color TYPE text USING category_color::text;
