-- Migration: Ensure RLS policies are correct for password_entries table to allow authenticated users to manage their own data. This is a safety measure to ensure the 'saving error' isn't due to permission issues.
-- Executed at: 2025-11-22T17:09:57Z
-- Generated by AI Agent

-- Ensure RLS is enabled
ALTER TABLE password_entries ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts
DROP POLICY IF EXISTS "Users can view their own entries" ON password_entries;
DROP POLICY IF EXISTS "Users can insert their own entries" ON password_entries;
DROP POLICY IF EXISTS "Users can update their own entries" ON password_entries;
DROP POLICY IF EXISTS "Users can delete their own entries" ON password_entries;

-- Re-create policies
CREATE POLICY "Users can view their own entries" 
ON password_entries FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own entries" 
ON password_entries FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own entries" 
ON password_entries FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own entries" 
ON password_entries FOR DELETE 
USING (auth.uid() = user_id);

